### PR TITLE
Maven

### PR DESCRIPTION
**Pull request by guusdk**
Our project uses JSTUN, but is transitioning from an Ant-based build environment to a Maven-based one. For this to work, we'd like to use JSTUN as a public Maven artifact.

Turning JSTUN into a Maven artifact involves two steps:

- Apply a Maven structure to the source code.
- publish the Maven-build JSTUN JAR file to a public Maven repository.

The first commit in this PR does the first: it applies a Maven structure, without introducing functional changes. The two other commits do introduce some minimal changes.

If you're interested, I'm willing to facilitate the second: publish this project into a public Maven repository. This will allow us, as well as others, to use this project with greater ease.

### CODE REVIEW

**Comment by tking** [comment]
Thanks

**Comment by guusdk** [comment]
Would you like my help to add this to Maven Central?

**Comment by tking** [comment]
This would be great and highly appreciated!

**Comment by guusdk** [comment]
Ok. I've set things in motion by applying for your namespace. The ticket is here: https://issues.sonatype.org/browse/OSSRH-31161

After this happens, we can deploy to the Sonatype repository, which syncs to central. I might be adding some pom.xml changes for this later.

**Comment by tking** [comment]
Cool! Thanks for pushing this!

**Pull request merged**
